# Generated by Django 3.2.6 on 2021-08-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchmovies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='search_date',
            field=models.DateField(auto_now=True),
        ),
    ]
