# Generated by Django 3.2.6 on 2021-08-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchmovies', '0002_alter_searchhistory_search_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='search_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
