# Generated by Django 3.2.6 on 2021-08-31 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchmovies', '0006_alter_searchhistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ('search_date',), 'verbose_name_plural': 'Search Histories'},
        ),
    ]
